/////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////
//            Galgomach
/////////////////////////////////////////////////////////////////////
//        Version 1
// Galgomach, 22nd level Demon Knight
//
// 
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Change Alignment
/////////////////////////////////////////////////////////////////////
IF
  !Allegiance(Myself,ENEMY)
  Global("MOBHA7_Enemy","GLOBAL",1)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Initial Set-Up
/////////////////////////////////////////////////////////////////////
IF
  Global("Prep","LOCALS",0)
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    SetGlobal("Prep","LOCALS",1)
    ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
    ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
    ReallyForceSpell(Myself,WIZARD_SPELL_SHIELD)
    ReallyForceSpell(Myself,WIZARD_TRUE_SIGHT)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)
    ReallyForceSpell(Myself,WIZARD_ABSOLUTE_IMMUNITY)
    ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
    ReallyForceSpell(Myself,CLERIC_RIGHTEOUS_MAGIC)
    SetGlobal("MO_DeathKnightFireballCast","LOCALS",0)
    XEquipItem("SW2H18",Myself,SLOT_WEAPON0,EQUIP)
END

IF
  Global("Prep","LOCALS",0)
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  DifficultyLT(HARDEST)
THEN
  RESPONSE #100
    SetGlobal("Prep","LOCALS",1)
    ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
    ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)
    ReallyForceSpell(Myself,WIZARD_TRUE_SIGHT)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_MANTLE)
    ReallyForceSpell(Myself,CLERIC_RIGHTEOUS_MAGIC)
    SetGlobal("MO_DeathKnightFireballCast","LOCALS",0)
    XEquipItem("SW2H17",Myself,SLOT_WEAPON1,EQUIP)
    DestroyItem("BRAC10")
    DestroyItem("AMUL21")
END

/////////////////////////////////////////////////////////////////////
// Spell: Vocalize
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  See([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  HaveSpell(WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
  StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Stoneskin
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  CheckStatLT(Myself,1,STONESKINS)
  HaveSpell(WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Improved Invisibility
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  CheckStatLT(Myself,2,STONESKINS)
  !HaveSpell(WIZARD_STONE_SKIN)
  HaveSpell(WIZARD_IMPROVED_INVISIBILITY)
  !CheckSpellState(Myself,CANNOT_TURN_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_IMPROVED_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Hunt Player
/////////////////////////////////////////////////////////////////////
IF
  !Detect([GOODCUTOFF])
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("MO_TeleportToPlayerTimer","LOCALS")
  CheckStatLT(Player1,1,SANCTUARY)
  !StateCheck(Player1,STATE_REALLY_DEAD)
  !StateCheck(Player1,STATE_INVISIBLE)
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_TeleportToPlayerTimer","LOCALS",ONE_ROUND)
    ReallyForceSpell(Player1,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (Dimension Door)
  RESPONSE #100
    Continue()
END

IF
  !Detect([GOODCUTOFF])
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("MO_TeleportToPlayerTimer","LOCALS")
  CheckStatLT(Player2,1,SANCTUARY)
  !StateCheck(Player2,STATE_REALLY_DEAD)
  !StateCheck(Player2,STATE_INVISIBLE)
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_TeleportToPlayerTimer","LOCALS",ONE_ROUND)
    ReallyForceSpell(Player2,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (Dimension Door)
  RESPONSE #100
    Continue()
END

IF
  !Detect([GOODCUTOFF])
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("MO_TeleportToPlayerTimer","LOCALS")
  CheckStatLT(Player3,1,SANCTUARY)
  !StateCheck(Player3,STATE_REALLY_DEAD)
  !StateCheck(Player3,STATE_INVISIBLE)
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_TeleportToPlayerTimer","LOCALS",ONE_ROUND)
    ReallyForceSpell(Player3,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (Dimension Door)
  RESPONSE #100
    Continue()
END

IF
  !Detect([GOODCUTOFF])
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("MO_TeleportToPlayerTimer","LOCALS")
  CheckStatLT(Player4,1,SANCTUARY)
  !StateCheck(Player4,STATE_REALLY_DEAD)
  !StateCheck(Player4,STATE_INVISIBLE)
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_TeleportToPlayerTimer","LOCALS",ONE_ROUND)
    ReallyForceSpell(Player4,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (Dimension Door)
  RESPONSE #100
    Continue()
END

IF
  !Detect([GOODCUTOFF])
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("MO_TeleportToPlayerTimer","LOCALS")
  CheckStatLT(Player5,1,SANCTUARY)
  !StateCheck(Player5,STATE_REALLY_DEAD)
  !StateCheck(Player5,STATE_INVISIBLE)
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_TeleportToPlayerTimer","LOCALS",ONE_ROUND)
    ReallyForceSpell(Player5,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (Dimension Door)
  RESPONSE #100
    Continue()
END

IF
  !Detect([GOODCUTOFF])
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("MO_TeleportToPlayerTimer","LOCALS")
  CheckStatLT(Player6,1,SANCTUARY)
  !StateCheck(Player6,STATE_REALLY_DEAD)
  !StateCheck(Player6,STATE_INVISIBLE)
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_TeleportToPlayerTimer","LOCALS",ONE_ROUND)
    ReallyForceSpell(Player6,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (Dimension Door)
  RESPONSE #100
    Continue()
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player1,1,SANCTUARY)
  !StateCheck(Player1,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",ONE_ROUND)
    MoveToObject(Player1)
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player2,1,SANCTUARY)
  !StateCheck(Player2,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",ONE_ROUND)
    MoveToObject(Player2)
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player3,1,SANCTUARY)
  !StateCheck(Player3,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",ONE_ROUND)
    MoveToObject(Player3)
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player4,1,SANCTUARY)
  !StateCheck(Player4,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",ONE_ROUND)
    MoveToObject(Player4)
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player5,1,SANCTUARY)
  !StateCheck(Player5,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",ONE_ROUND)
    MoveToObject(Player5)
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player6,1,SANCTUARY)
  !StateCheck(Player6,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",ONE_ROUND)
    MoveToObject(Player6)
END

IF
    GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
    !Detect([GOODCUTOFF])
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
END

/////////////////////////////////////////////////////////////////////
// Spell: Spell Turning
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  OR(7)
    See([GOODCUTOFF.0.0.MAGE_ALL])
    See([GOODCUTOFF.0.0.BARD_ALL])
    See([GOODCUTOFF.0.0.CLERIC_ALL])
    See([GOODCUTOFF.0.0.DRUID_ALL])
    See([GOODCUTOFF.0.0.SORCERER])
    See([GOODCUTOFF.0.0.CLERIC_MAGE])
    See([GOODCUTOFF.0.0.MAGE_ALL])
  HaveSpell(WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
  CheckStatLT(Myself,1,WIZARD_SPELL_TURNING)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #50
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Globe of Invulnerability
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  OR(7)
    See([GOODCUTOFF.0.0.MAGE_ALL])
    See([GOODCUTOFF.0.0.BARD_ALL])
    See([GOODCUTOFF.0.0.CLERIC_ALL])
    See([GOODCUTOFF.0.0.DRUID_ALL])
    See([GOODCUTOFF.0.0.SORCERER])
    See([GOODCUTOFF.0.0.CLERIC_MAGE])
    See([GOODCUTOFF.0.0.MAGE_ALL])
  HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)  // SPWI602.SPL (Globe of Invulnerability)
  !CheckStatGT(Myself,0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #50
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)  // SPWI602.SPL (Globe of Invulnerability)
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Minor Spell Turning
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  OR(7)
    See([GOODCUTOFF.0.0.MAGE_ALL])
    See([GOODCUTOFF.0.0.BARD_ALL])
    See([GOODCUTOFF.0.0.CLERIC_ALL])
    See([GOODCUTOFF.0.0.DRUID_ALL])
    See([GOODCUTOFF.0.0.SORCERER])
    See([GOODCUTOFF.0.0.CLERIC_MAGE])
    See([GOODCUTOFF.0.0.MAGE_ALL])
  HaveSpell(WIZARD_MINOR_SPELL_TURNING)  // SPWI522.SPL (Minor Spell Turning)
  CheckStatLT(Myself,1,WIZARD_SPELL_TURNING)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #50
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_MINOR_SPELL_TURNING)  // SPWI522.SPL (Minor Spell Turning)
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Mirror Image
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
  !StateCheck(Myself,STATE_MIRRORIMAGE)
  !CheckStatGT(NearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(SeventhNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(EighthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(NinthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(TenthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #50
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Remove Magic
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Global("MO_RemoveMagic","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",24)
    SetGlobal("MO_RemoveMagic","LOCALS",1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  Global("MO_RemoveMagic","LOCALS",0)
  See(SecondNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Global("MO_RemoveMagic","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",24)
    SetGlobal("MO_RemoveMagic","LOCALS",1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  See(ThirdNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Global("MO_RemoveMagic","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",24)
    SetGlobal("MO_RemoveMagic","LOCALS",1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  See(FourthNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Global("MO_RemoveMagic","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",24)
    SetGlobal("MO_RemoveMagic","LOCALS",1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  See(FifthNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Global("MO_RemoveMagic","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",24)
    SetGlobal("MO_RemoveMagic","LOCALS",1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  See(SixthNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Global("MO_RemoveMagic","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",24)
    SetGlobal("MO_RemoveMagic","LOCALS",1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Power Word Kill
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_PWKTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_KILL)
  HPLT(SixthNearestEnemyOf(Myself),61)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_PWKTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_KILL)
  HPLT(FifthNearestEnemyOf(Myself),61)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_PWKTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_KILL)
  HPLT(FourthNearestEnemyOf(Myself),61)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_PWKTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_KILL)
  HPLT(ThirdNearestEnemyOf(Myself),61)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_PWKTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_KILL)
  HPLT(SecondNearestEnemyOf(Myself),61)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_PWKTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_KILL)
  HPLT(NearestEnemyOf(Myself),61)
  !CheckSpellState(NearestEnemyOf(Myself),SI_CONJURATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),25,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_PWKTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_KILL)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HPLT(LastSeenBy(Myself),61)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_PWKTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_KILL)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Chaos
/////////////////////////////////////////////////////////////////////
IF  
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChaosTimer","LOCALS")
  HaveSpell(WIZARD_CHAOS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(SixthNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(SixthNearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(SixthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",SixthNearestEnemyOf(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",SixthNearestEnemyOf(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",SixthNearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",SixthNearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",SixthNearestEnemyOf(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",SixthNearestEnemyOf(Myself)) // Psion's Blade +5
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF  
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChaosTimer","LOCALS")
  HaveSpell(WIZARD_CHAOS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(FifthNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(FifthNearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(FifthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",FifthNearestEnemyOf(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",FifthNearestEnemyOf(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",FifthNearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",FifthNearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",FifthNearestEnemyOf(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",FifthNearestEnemyOf(Myself)) // Psion's Blade +5
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF  
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChaosTimer","LOCALS")
  HaveSpell(WIZARD_CHAOS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(FourthNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(FourthNearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(FourthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",FourthNearestEnemyOf(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",FourthNearestEnemyOf(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",FourthNearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",FourthNearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",FourthNearestEnemyOf(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",FourthNearestEnemyOf(Myself)) // Psion's Blade +5
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF  
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChaosTimer","LOCALS")
  HaveSpell(WIZARD_CHAOS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(ThirdNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(ThirdNearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",ThirdNearestEnemyOf(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",ThirdNearestEnemyOf(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",ThirdNearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",ThirdNearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",ThirdNearestEnemyOf(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",ThirdNearestEnemyOf(Myself)) // Psion's Blade +5
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF  
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChaosTimer","LOCALS")
  HaveSpell(WIZARD_CHAOS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(SecondNearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(SecondNearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(SecondNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",SecondNearestEnemyOf(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",SecondNearestEnemyOf(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",SecondNearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",SecondNearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",SecondNearestEnemyOf(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",SecondNearestEnemyOf(Myself)) // Psion's Blade +5
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF  
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChaosTimer","LOCALS")
  HaveSpell(WIZARD_CHAOS)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
  CheckStatLT(NearestEnemyOf(Myself),20,RESISTMAGIC)
  CheckStatGT(NearestEnemyOf(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(NearestEnemyOf(Myself),SI_ENCHANTMENT)
  !CheckSpellState(NearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(NearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(NearestEnemyOf(Myself),POTION_OF_CLARITY)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",NearestEnemyOf(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",NearestEnemyOf(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",NearestEnemyOf(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",NearestEnemyOf(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",NearestEnemyOf(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",NearestEnemyOf(Myself)) // Psion's Blade +5
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ChaosTimer","LOCALS")
  HaveSpell(WIZARD_CHAOS)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_DISABLED)
  CheckStatLT(LastSeenBy(Myself),20,RESISTMAGIC)
  CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),POTION_OF_CLARITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",LastSeenBy(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",LastSeenBy(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",LastSeenBy(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",LastSeenBy(Myself)) // Psion's Blade +5
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_ChaosTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_CHAOS)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Power Word Stun
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPLT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),90)
  HPPercentLT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),60)
  !Gender(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),SUMMONED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),BERSERKER_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),MINSC_BERSERK)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),CHAOTIC_COMMANDS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),SI_CONJURATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),0,SANCTUARY)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),STATE_HARMLESS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPLT([GOODCUTOFF.0.0.DRUID_ALL],90)
  HPPercentLT([GOODCUTOFF.0.0.DRUID_ALL],60)
  !Gender([GOODCUTOFF.0.0.DRUID_ALL],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.DRUID_ALL],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.DRUID_ALL],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.DRUID_ALL],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.DRUID_ALL],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.DRUID_ALL],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.DRUID_ALL],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.DRUID_ALL],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState([GOODCUTOFF.0.0.DRUID_ALL],CHAOTIC_COMMANDS)
  !CheckSpellState([GOODCUTOFF.0.0.DRUID_ALL],SI_CONJURATION)
  !StateCheck([GOODCUTOFF.0.0.DRUID_ALL],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.DRUID_ALL],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.DRUID_ALL],0,SANCTUARY)
  !StateCheck([GOODCUTOFF.0.0.DRUID_ALL],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.DRUID_ALL],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.DRUID_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPLT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),90)
  HPPercentLT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),60)
  !Gender(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),SUMMONED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),BERSERKER_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),MINSC_BERSERK)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),CHAOTIC_COMMANDS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),SI_CONJURATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),0,SANCTUARY)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),STATE_HARMLESS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPLT([GOODCUTOFF.0.0.CLERIC_ALL],90)
  HPPercentLT([GOODCUTOFF.0.0.CLERIC_ALL],60)
  !Gender([GOODCUTOFF.0.0.CLERIC_ALL],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.CLERIC_ALL],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.CLERIC_ALL],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.CLERIC_ALL],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.CLERIC_ALL],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.CLERIC_ALL],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.CLERIC_ALL],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.CLERIC_ALL],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState([GOODCUTOFF.0.0.CLERIC_ALL],CHAOTIC_COMMANDS)
  !CheckSpellState([GOODCUTOFF.0.0.CLERIC_ALL],SI_CONJURATION)
  !StateCheck([GOODCUTOFF.0.0.CLERIC_ALL],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.CLERIC_ALL],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.CLERIC_ALL],0,SANCTUARY)
  !StateCheck([GOODCUTOFF.0.0.CLERIC_ALL],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.CLERIC_ALL],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.CLERIC_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPLT(SecondNearest([GOODCUTOFF.0.0.THIEF]),90)
  HPPercentLT(SecondNearest([GOODCUTOFF.0.0.THIEF]),60)
  !Gender(SecondNearest([GOODCUTOFF.0.0.THIEF]),SUMMONED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),BERSERKER_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),MINSC_BERSERK)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),CHAOTIC_COMMANDS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),SI_CONJURATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.THIEF]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.THIEF]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),0,SANCTUARY)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.THIEF]),STATE_HARMLESS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.THIEF]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPLT([GOODCUTOFF.0.0.THIEF],90)
  HPPercentLT([GOODCUTOFF.0.0.THIEF],60)
  !Gender([GOODCUTOFF.0.0.THIEF],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.THIEF],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.THIEF],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.THIEF],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.THIEF],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],CHAOTIC_COMMANDS)
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],SI_CONJURATION)
  !StateCheck([GOODCUTOFF.0.0.THIEF],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.THIEF],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],0,SANCTUARY)
  !StateCheck([GOODCUTOFF.0.0.THIEF],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.THIEF])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPLT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),90)
  HPPercentLT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),60)
  !Gender(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),SUMMONED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),BERSERKER_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),MINSC_BERSERK)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),CHAOTIC_COMMANDS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),SI_CONJURATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),0,SANCTUARY)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),STATE_HARMLESS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPLT([GOODCUTOFF.0.0.BARD_ALL],90)
  HPPercentLT([GOODCUTOFF.0.0.BARD_ALL],60)
  !Gender([GOODCUTOFF.0.0.BARD_ALL],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.BARD_ALL],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.BARD_ALL],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.BARD_ALL],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.BARD_ALL],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.BARD_ALL],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.BARD_ALL],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.BARD_ALL],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState([GOODCUTOFF.0.0.BARD_ALL],CHAOTIC_COMMANDS)
  !CheckSpellState([GOODCUTOFF.0.0.BARD_ALL],SI_CONJURATION)
  !StateCheck([GOODCUTOFF.0.0.BARD_ALL],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.BARD_ALL],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.BARD_ALL],0,SANCTUARY)
  !StateCheck([GOODCUTOFF.0.0.BARD_ALL],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.BARD_ALL],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.BARD_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPLT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),90)
  HPPercentLT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),60)
  !Gender(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),SUMMONED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),BERSERKER_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),MINSC_BERSERK)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),CHAOTIC_COMMANDS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),SI_CONJURATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),0,SANCTUARY)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),STATE_HARMLESS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPLT([GOODCUTOFF.0.0.MAGE_ALL],90)
  HPPercentLT([GOODCUTOFF.0.0.MAGE_ALL],60)
  !Gender([GOODCUTOFF.0.0.MAGE_ALL],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_ALL],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_ALL],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_ALL],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.MAGE_ALL],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.MAGE_ALL],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.MAGE_ALL],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.MAGE_ALL],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_ALL],CHAOTIC_COMMANDS)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_ALL],SI_CONJURATION)
  !StateCheck([GOODCUTOFF.0.0.MAGE_ALL],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.MAGE_ALL],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_ALL],0,SANCTUARY)
  !StateCheck([GOODCUTOFF.0.0.MAGE_ALL],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_ALL],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.MAGE_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPLT([GOODCUTOFF.0.0.MAGE_THIEF],90)
  HPPercentLT([GOODCUTOFF.0.0.MAGE_THIEF],60)
  !Gender([GOODCUTOFF.0.0.MAGE_THIEF],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_THIEF],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_THIEF],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_THIEF],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.MAGE_THIEF],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.MAGE_THIEF],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.MAGE_THIEF],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.MAGE_THIEF],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_THIEF],CHAOTIC_COMMANDS)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_THIEF],SI_CONJURATION)
  !StateCheck([GOODCUTOFF.0.0.MAGE_THIEF],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.MAGE_THIEF],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_THIEF],0,SANCTUARY)
  !StateCheck([GOODCUTOFF.0.0.MAGE_THIEF],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_THIEF],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.MAGE_THIEF])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPLT([GOODCUTOFF.0.0.MAGE],90)
  HPPercentLT([GOODCUTOFF.0.0.MAGE],60)
  !Gender([GOODCUTOFF.0.0.MAGE],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.MAGE],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.MAGE],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.MAGE],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.MAGE],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE],CHAOTIC_COMMANDS)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE],SI_CONJURATION)
  !StateCheck([GOODCUTOFF.0.0.MAGE],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.MAGE],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE],0,SANCTUARY)
  !StateCheck([GOODCUTOFF.0.0.MAGE],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.MAGE])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_STUN)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HPLT(LastSeenBy(Myself),90)
  HPPercentLT(LastSeenBy(Myself),60)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_StunTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Demon Knight Fireball
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_DeathKnightFireballCast","LOCALS",0)
  !HasItem("clck26",SixthNearestEnemyOf(Myself))
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTFIRE)
  CheckStatLT(SixthNearestEnemyOf(Myself),25,RESISTMAGIC)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_DeathKnightFireballCast","LOCALS",0)
  !HasItem("clck26",FifthNearestEnemyOf(Myself))
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTFIRE)
  CheckStatLT(FifthNearestEnemyOf(Myself),25,RESISTMAGIC)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_DeathKnightFireballCast","LOCALS",0)
  !HasItem("clck26",FourthNearestEnemyOf(Myself))
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTFIRE)
  CheckStatLT(FourthNearestEnemyOf(Myself),25,RESISTMAGIC)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_DeathKnightFireballCast","LOCALS",0)
  !HasItem("clck26",ThirdNearestEnemyOf(Myself))
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTFIRE)
  CheckStatLT(ThirdNearestEnemyOf(Myself),25,RESISTMAGIC)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_DeathKnightFireballCast","LOCALS",0)
  !HasItem("clck26",SecondNearestEnemyOf(Myself))
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTFIRE)
  CheckStatLT(SecondNearestEnemyOf(Myself),25,RESISTMAGIC)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_DeathKnightFireballCast","LOCALS",0)
  !HasItem("clck26",NearestEnemyOf(Myself))
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTFIRE)
  CheckStatLT(NearestEnemyOf(Myself),25,RESISTMAGIC)
  !CheckStatGT(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_DeathKnightFireballCast","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItem("clck26",LastSeenBy(Myself))
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobal("MO_DeathKnightFireballCast","LOCALS",1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),DEATHKNIGHT_FIREBALL)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Symbol Fear
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_FearSymbolTimer","LOCALS")
  OR(2)
    HaveSpell(WIZARD_SYMBOL_FEAR)
    HaveSpell(WIZARD_NPC_SYMBOL_FEAR)
  !Kit(SixthNearestEnemyOf(Myself),CAVALIER)
  !General(SixthNearestEnemyOf(Myself),UNDEAD)
  !Kit(SixthNearestEnemyOf(Myself),Blackguard)
  CheckStatGT(SixthNearestEnemyOf(Myself),4,SAVEVSSPELL)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_CONJURATION)
  !CheckSpellState(SixthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),MINSC_BERSERK)
  !CheckSpellState(SixthNearestEnemyOf(Myself),RESIST_FEAR)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(SixthNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_FearSymbolTimer","LOCALS")
  OR(2)
    HaveSpell(WIZARD_SYMBOL_FEAR)
    HaveSpell(WIZARD_NPC_SYMBOL_FEAR)
  !Kit(FifthNearestEnemyOf(Myself),CAVALIER)
  !General(FifthNearestEnemyOf(Myself),UNDEAD)
  !Kit(FifthNearestEnemyOf(Myself),Blackguard)
  CheckStatGT(FifthNearestEnemyOf(Myself),4,SAVEVSSPELL)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_CONJURATION)
  !CheckSpellState(FifthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),MINSC_BERSERK)
  !CheckSpellState(FifthNearestEnemyOf(Myself),RESIST_FEAR)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(FifthNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_FearSymbolTimer","LOCALS")
  OR(2)
    HaveSpell(WIZARD_SYMBOL_FEAR)
    HaveSpell(WIZARD_NPC_SYMBOL_FEAR)
  !Kit(FourthNearestEnemyOf(Myself),CAVALIER)
  !General(FourthNearestEnemyOf(Myself),UNDEAD)
  !Kit(FourthNearestEnemyOf(Myself),Blackguard)
  CheckStatGT(FourthNearestEnemyOf(Myself),4,SAVEVSSPELL)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_CONJURATION)
  !CheckSpellState(FourthNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),MINSC_BERSERK)
  !CheckSpellState(FourthNearestEnemyOf(Myself),RESIST_FEAR)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(FourthNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_FearSymbolTimer","LOCALS")
  OR(2)
    HaveSpell(WIZARD_SYMBOL_FEAR)
    HaveSpell(WIZARD_NPC_SYMBOL_FEAR)
  !Kit(ThirdNearestEnemyOf(Myself),CAVALIER)
  !General(ThirdNearestEnemyOf(Myself),UNDEAD)
  !Kit(ThirdNearestEnemyOf(Myself),Blackguard)
  CheckStatGT(ThirdNearestEnemyOf(Myself),4,SAVEVSSPELL)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_CONJURATION)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),MINSC_BERSERK)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),RESIST_FEAR)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_FearSymbolTimer","LOCALS")
  OR(2)
    HaveSpell(WIZARD_SYMBOL_FEAR)
    HaveSpell(WIZARD_NPC_SYMBOL_FEAR)
  !Kit(SecondNearestEnemyOf(Myself),CAVALIER)
  !General(SecondNearestEnemyOf(Myself),UNDEAD)
  !Kit(SecondNearestEnemyOf(Myself),Blackguard)
  CheckStatGT(SecondNearestEnemyOf(Myself),4,SAVEVSSPELL)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_CONJURATION)
  !CheckSpellState(SecondNearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),MINSC_BERSERK)
  !CheckSpellState(SecondNearestEnemyOf(Myself),RESIST_FEAR)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(SecondNearestEnemyOf(Myself),25,RESISTMAGIC)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_FearSymbolTimer","LOCALS")
  OR(2)
    HaveSpell(WIZARD_SYMBOL_FEAR)
    HaveSpell(WIZARD_NPC_SYMBOL_FEAR)
  !Kit(NearestEnemyOf(Myself),CAVALIER)
  !General(NearestEnemyOf(Myself),UNDEAD)
  !Kit(NearestEnemyOf(Myself),Blackguard)
  CheckStatGT(NearestEnemyOf(Myself),4,SAVEVSSPELL)
  !CheckSpellState(NearestEnemyOf(Myself),SI_CONJURATION)
  !CheckSpellState(NearestEnemyOf(Myself),BARBARIAN_RAGE)
  !CheckSpellState(NearestEnemyOf(Myself),BERSERKER_RAGE)
  !CheckSpellState(NearestEnemyOf(Myself),MINSC_BERSERK)
  !CheckSpellState(NearestEnemyOf(Myself),RESIST_FEAR)
  !CheckStatGT(NearestEnemyOf(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(NearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(NearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(NearestEnemyOf(Myself),STATE_HARMLESS)
  !CheckStatGT(NearestEnemyOf(Myself),25,RESISTMAGIC)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_FearSymbolTimer","LOCALS")
  HaveSpell(WIZARD_SYMBOL_FEAR)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !Kit(LastSeenBy(Myself),CAVALIER)
  !General(LastSeenBy(Myself),UNDEAD)
  !Kit(LastSeenBy(Myself),Blackguard)
  CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  !CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_FearSymbolTimer","LOCALS",12)
    RemoveSpell(WIZARD_SYMBOL_FEAR)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_NPC_SYMBOL_FEAR)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_FearSymbolTimer","LOCALS")
  HaveSpell(WIZARD_NPC_SYMBOL_FEAR)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !Kit(LastSeenBy(Myself),CAVALIER)
  !General(LastSeenBy(Myself),UNDEAD)
  !Kit(LastSeenBy(Myself),Blackguard)
  CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  !CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_FearSymbolTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_NPC_SYMBOL_FEAR)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Magic Missile
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),ENTROPY_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(SecondNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),ENTROPY_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(ThirdNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),ENTROPY_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(FourthNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),ENTROPY_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(FifthNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),ENTROPY_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(SixthNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),ENTROPY_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Attack
/////////////////////////////////////////////////////////////////////
IF
  OR(6)
    See(Player1)
    See(Player2)
    See(Player3)
    See(Player4)
    See(Player5)
    See(Player6)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  Range(SixthNearestEnemyOf(Myself),5)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  Range(FifthNearestEnemyOf(Myself),5)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  Range(FourthNearestEnemyOf(Myself),5)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  Range(ThirdNearestEnemyOf(Myself),5)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  Range(SecondNearestEnemyOf(Myself),5)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(NearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  Range(NearestEnemyOf(Myself),5)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(SixthNearestEnemyOf(Myself),80,RESISTSLASHING)
  Range(SixthNearestEnemyOf(Myself),5)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(FifthNearestEnemyOf(Myself),80,RESISTSLASHING)
  Range(FifthNearestEnemyOf(Myself),5)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(FourthNearestEnemyOf(Myself),80,RESISTSLASHING)
  Range(FourthNearestEnemyOf(Myself),5)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(ThirdNearestEnemyOf(Myself),80,RESISTSLASHING)
  Range(ThirdNearestEnemyOf(Myself),5)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(SecondNearestEnemyOf(Myself),80,RESISTSLASHING)
  Range(SecondNearestEnemyOf(Myself),5)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(NearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(NearestEnemyOf(Myself),80,RESISTSLASHING)
  Range(NearestEnemyOf(Myself),5)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(SixthNearestEnemyOf(Myself),STATE_IMMOBILE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(FifthNearestEnemyOf(Myself),STATE_IMMOBILE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(FourthNearestEnemyOf(Myself),STATE_IMMOBILE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMMOBILE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  StateCheck(SecondNearestEnemyOf(Myself),STATE_IMMOBILE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  StateCheck(NearestEnemyOf(Myself),STATE_IMMOBILE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
  WeaponCanDamage(LastSeenBy(Myself),MAINHAND)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,49)
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),30)
END

IF
  !Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  Allegiance(LastSeenBy(Myself),ENEMY)
  WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
  WeaponCanDamage(LastSeenBy(Myself),MAINHAND)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,49)
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),30)
END

/////////////////////////////////////////////////////////////////////
// Find them! (Experimental)
/////////////////////////////////////////////////////////////////////
IF
  ActionListEmpty()
  See(Player1)
  !See(Player2)
  Allegiance(Myself,ENEMY)
  !WeaponEffectiveVs(Player1,MAINHAND)
  !WeaponCanDamage(Player1,MAINHAND)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player2)
END

IF
  ActionListEmpty()
  See(Player2)
  !See(Player3)
  Allegiance(Myself,ENEMY)
  !WeaponEffectiveVs(Player2,MAINHAND)
  !WeaponCanDamage(Player2,MAINHAND)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player3)
END

IF
  ActionListEmpty()
  See(Player3)
  !See(Player4)
  Allegiance(Myself,ENEMY)
  !WeaponEffectiveVs(Player3,MAINHAND)
  !WeaponCanDamage(Player3,MAINHAND)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player4)
END

IF
  ActionListEmpty()
  See(Player4)
  !See(Player5)
  Allegiance(Myself,ENEMY)
  !WeaponEffectiveVs(Player4,MAINHAND)
  !WeaponCanDamage(Player4,MAINHAND)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player5)
END

IF
  ActionListEmpty()
  See(Player5)
  !See(Player6)
  Allegiance(Myself,ENEMY)
  !WeaponEffectiveVs(Player5,MAINHAND)
  !WeaponCanDamage(Player5,MAINHAND)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player6)
END

IF
  ActionListEmpty()
  See(Player6)
  !See(Player1)
  Allegiance(Myself,ENEMY)
  !WeaponEffectiveVs(Player6,MAINHAND)
  !WeaponCanDamage(Player6,MAINHAND)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player1)
END

IF
  ActionListEmpty()
  AttackedBy([ANYONE],DEFAULT)
  InWeaponRange(LastSeenBy(Myself))
THEN
  RESPONSE #100
    Attack(LastAttackerOf(Myself))
END

IF
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    MoveToObject(LastSeenBy(Myself))
END