/////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////
//            Zendrilar
/////////////////////////////////////////////////////////////////////
//        Version 1
// Archlich, 31-22 Cleric/Mage
//
// Memorized Cleric Spells By Level: 10 9 10 10 9 8 6
// Memorized Cleric Spells (number, name, spell level): 
//  5 armor of faith (1)
//  1 doom (1)
//  4 protection from evil (1)
//
//  3 draw upon holy might (2)
//  2 flame blade (2)
//  2 resist fire and cold (2)
//  2 slow poison (2)
// 
//  4 animate dead (3)
//  3 glyph of warding (3)
//  2 protection from fire (3)
//  1 zone of sweat air (3)
//
//  4 cure serous wounds (4)
//  3 free action (4)
//  1 neutralize poison (4)
//  2 protection from evil, 10' radius (4)
//
//  9 mass cure (5)
//
//  2 aerial servant (6)
//  1 conjure animals (6)
//  3 heal (6)
//  2 wondrous recall (6)
//
//  3 regeneration (7)
//  1 globe of blades (7)
//  2 unholy word (7)
//
// Memorized Mage Spells By Level: 5 5 5 7 6 10 6 7 7
// Memorized Mage Spells (number, name, spell level): 
//  5 larloch's minor drain (1)
//
//  4 melf acid (2)   
//  1 vocalize (2)
//
//  3 remove magic (3)
//  2 slow (3)
//
//  2 greater malison (4)
//  1 Fireshield Blue (4)
//  1 Teleport Field (4)
//  1 improved invisibility (4)
//  2 contagion (4)
//
//  1 Shadow Door (5)
//  3 spell immunity (5)
//  2 breach (5)
//
//  2 improved haste (6)
//  4 Death Spell (6)
//  2 protection from magic energy (6)
//  2 protection from magical weapons (6)
//
//  1 protection from the elements (7)
//  2 power word, stun (7)
//  3 ruby ray of reversal (7)
//
//  7 Maze (8)
//  0 Power Word, Blind (8) <- This will crash the game if the last 
//  Player surviving has PW Blind on
//
//  1 Time Stop (9)
//  1 Improved Alacrity (9)
//  2 energy drain (9)
//  3 bigby's crushing hand (9)
//
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Truesight Timer
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_EnemyTrueSightTimer","GLOBAL")
  Global("MO_EnemyTrueSight","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("MO_EnemyTrueSight","GLOBAL",0)
END

IF
  Global("MO_TrueSightActive","LOCALS",1)
  CheckStat(Myself,0,TRUE_SIGHT)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",0)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",0)
END

/////////////////////////////////////////////////////////////////////
// Prep
/////////////////////////////////////////////////////////////////////
IF
  Global("Prep","LOCALS",0)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
    ReallyForceSpell(Myself,WIZARD_SPELL_SHIELD)  // SPWI519.SPL (Spell Shield)
    ReallyForceSpell(Myself,CLERIC_SHIELD_OF_THE_ARCHONS)  // SPPR701.SPL (Shield of the Archons)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_MANTLE)  
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_THE_ELEMENTS)  // SPWI702.SPL (Protection From The Elements)
    ReallyForceSpell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
    ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
    ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)  // SPWI592.SPL (Immunity: Divination)
    ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)
    //ReallyForceSpell(Myself,WIZARD_MELF_METEOR)
    ReallyForceSpell(Myself,CLERIC_GLOBE_OF_BLADES)
    ReallyForceSpell(Myself,CLERIC_ARMOR_OF_FAITH)
    SetGlobal("MO_Larloch","LOCALS",5)
    SetGlobal("MO_SweetAir","LOCALS",1)
    SetGlobal("MO_Vocalize","LOCALS",1)
    //SetGlobal("MO_MelfMeteor","LOCALS",3)
    SetGlobal("MO_RemoveMagic","LOCALS",3)
    SetGlobal("MO_Slow","LOCALS",2)
    SetGlobal("MO_Teleport","LOCALS",1)
    SetGlobal("MO_Malison","LOCALS",2)
    SetGlobal("MO_Contagion","LOCALS",2)
    SetGlobal("MO_ShadowDoor","LOCALS",1)
    SetGlobal("MO_Breach","LOCALS",2)
    SetGlobal("MO_SpellImmunity","LOCALS",3)
    SetGlobal("MO_PfMW","LOCALS",2)
    SetGlobal("MO_ProtElements","LOCALS",1)
    SetGlobal("MO_WondrousRecall","LOCALS",2)
    SetGlobal("MO_DeathSpell","LOCALS",4)
    SetGlobal("MO_RubyRay","LOCALS",3)
    SetGlobal("MO_Maze","LOCALS",7)
    SetGlobal("MO_UnholyWord","LOCALS",2)
    SetGlobal("MO_PowerWordStun","LOCALS",2)
    SetGlobal("MO_PowerWordBlind","LOCALS",0)
    SetGlobal("MO_EnergyDrain","LOCALS",2)
    //SetGlobal("MO_BigbysCrushingHand","LOCALS",5)
    SetGlobal("MO_ImprovedAlacrity","LOCALS",1)
    SetGlobal("MO_TimeStop","LOCALS",1)
    SetGlobal("Prep","LOCALS",1)
END

IF
  DifficultyLT(HARDEST)
  Global("MO_CheckDifficulty","LOCALS",0) 
THEN 
  RESPONSE #100
    SetGlobal("MO_CheckDifficulty","LOCALS",1)
    DestroyItem("WA2ROBE")
    DestroyItem("AMUL21")
END

IF
  DifficultyGT(HARD)
  Global("MO_CheckDifficulty","LOCALS",0) 
THEN 
  RESPONSE #100
    SetGlobal("MO_CheckDifficulty","LOCALS",1)
END

/////////////////////////////////////////////////////////////////////
// Contingency
/////////////////////////////////////////////////////////////////////
IF
  Global("Contingency","LOCALS",0)
  TookDamage()
THEN
  RESPONSE #100
    ApplySpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)  // SPWI592.SPL (Immunity: Divination)
    ApplySpell(Myself,WIZARD_MISLEAD)  // SPWI607.SPL (Mislead)
    ApplySpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
    SetGlobal("Contingency","LOCALS",1)
END

/////////////////////////////////////////////////////////////////////
// Spell Trigger
/////////////////////////////////////////////////////////////////////
IF
  See(FarthestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),35,RESISTMAGIC)
  Global("SpellTrigger","LOCALS",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_ICE_STORM)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SKULL_TRAP)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_DEATH_FOG)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
END

IF
  See(SecondFarthestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),35,RESISTMAGIC)
  Global("SpellTrigger","LOCALS",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_ICE_STORM)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SKULL_TRAP)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_DEATH_FOG)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
END

IF
  See(ThirdFarthestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),35,RESISTMAGIC)
  Global("SpellTrigger","LOCALS",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_ICE_STORM)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SKULL_TRAP)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_DEATH_FOG)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Defensive
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(NearestEnemyOf(Myself))
  GlobalGT("MO_PfMW","LOCALS",0)
  !CheckSpellState(Myself,PROTECTION_FROM_MAGICAL_WEAPONS)
  !CheckSpellState(Myself,ABSOLUTE_IMMUNITY)
  !CheckSpellState(Myself,MANTLE)
  !CheckSpellState(Myself,IMPROVED_MANTLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_PfMW","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See([GOODCUTOFF])
  GlobalGT("MO_Vocalize","LOCALS",0)
  StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_Vocalize","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Spell Immunity
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_SpellImmunity","LOCALS",0)
  See([GOODCUTOFF])
  !CheckSpellState(Myself,SI_DIVINATION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_SpellImmunity","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)  // SPWI592.SPL (Immunity: Divination)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_SpellImmunity","LOCALS",0)
  See([GOODCUTOFF])
  !CheckSpellState(Myself,SI_ABJURATION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_SpellImmunity","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Protection from the Elements
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(NearestEnemyOf(Myself))
  GlobalGT("MO_ProtElements","LOCALS",0)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_ENERGY)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_THE_ELEMENTS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_ProtElements","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_PROTECTION_FROM_THE_ELEMENTS)  // SPWI702.SPL (Protection From The Elements)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Zone of Sweet Air
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_SweetAir","LOCALS",0)
  OR(12)
    SpellCast([GOODCUTOFF.0.0.MAGE_ALL],WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
    SpellCast([GOODCUTOFF.0.0.MAGE_ALL],WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
    SpellCast([GOODCUTOFF.0.0.MAGE_ALL],WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
    SpellCast([GOODCUTOFF.0.0.MAGE_ALL],WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
    SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
    SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
    SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
    SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
    SpellCast([GOODCUTOFF.0.0.SHAMAN],CLERIC_WRITHING_FOG)  // SPPR250.SPL (Writhing Fog)
    SpellCast([GOODCUTOFF],TRAP_STINKING_CLOUD)  // SPWI004.SPL (Stinking Cloud)
    SpellCast([GOODCUTOFF],SPORE_DEATH)  // SPIN673.SPL (Cloudkill)
    SpellCast([GOODCUTOFF],TRAP_CLOUDKILL)  // SPWI016.SPL (Cloudkill)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_SweetAir","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MO_WondrousRecallCounter","LOCALS",1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Clear Insects
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Allegiance(Myself,ENEMY)
  See(NearestAllyOf(Myself))
  Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
  GlobalGT("MO_DeathSpell","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_DeathSpell","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Allegiance(Myself,ENEMY)
  See(SecondNearestAllyOf(Myself))
  Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
  GlobalGT("MO_DeathSpell","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_DeathSpell","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Allegiance(Myself,ENEMY)
  See(ThirdNearestAllyOf(Myself))
  Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
  GlobalGT("MO_DeathSpell","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_DeathSpell","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Allegiance(Myself,ENEMY)
  See(FourthNearestAllyOf(Myself))
  Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
  GlobalGT("MO_DeathSpell","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_DeathSpell","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Allegiance(Myself,ENEMY)
  See(FifthNearestAllyOf(Myself))
  Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
  GlobalGT("MO_DeathSpell","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_DeathSpell","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Allegiance(Myself,ENEMY)
  See(SixthNearestAllyOf(Myself))
  Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
  GlobalGT("MO_DeathSpell","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_DeathSpell","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Hunt the Player
/////////////////////////////////////////////////////////////////////
IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player1,1,SANCTUARY)
  !StateCheck(Player1,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",ONE_ROUND)
    MoveToObject(Player1)
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player2,1,SANCTUARY)
  !StateCheck(Player2,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",ONE_ROUND)
    MoveToObject(Player2)
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player3,1,SANCTUARY)
  !StateCheck(Player3,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",ONE_ROUND)
    MoveToObject(Player3)
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player4,1,SANCTUARY)
  !StateCheck(Player4,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",ONE_ROUND)
    MoveToObject(Player4)
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player5,1,SANCTUARY)
  !StateCheck(Player5,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",ONE_ROUND)
    MoveToObject(Player5)
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    TookDamage()
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player6,1,SANCTUARY)
  !StateCheck(Player6,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",ONE_ROUND)
    MoveToObject(Player6)
END

IF
    GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
    !Detect([GOODCUTOFF])
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
END

/////////////////////////////////////////////////////////////////////
// Spell: Timestop
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  GlobalGT("MO_TimeStop","LOCALS",0)
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_TimeStop","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_TimeStopTimer","LOCALS",30)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_TIME_STOP)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Improved Alactrity - Used ONLY after Time Stop
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  GlobalGT("MO_ImprovedAlacrity","LOCALS",0)
  OR(2)
    See(NearestEnemyOf(Myself))
    ActuallyInCombat()
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_ImprovedAlacrity","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (Improved Alacrity)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Remove Magic
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  GlobalGT("MO_RemoveMagic","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_RemoveMagic","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",18)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  See(SecondNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  GlobalGT("MO_RemoveMagic","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_RemoveMagic","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",18)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  See(ThirdNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  GlobalGT("MO_RemoveMagic","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_RemoveMagic","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",18)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  See(FourthNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  GlobalGT("MO_RemoveMagic","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_RemoveMagic","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",18)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  See(FifthNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  GlobalGT("MO_RemoveMagic","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_RemoveMagic","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",18)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  See(SixthNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  GlobalGT("MO_RemoveMagic","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_RemoveMagic","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",18)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Breach
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  See(NearestEnemyOf(Myself))
  GlobalGT("MO_Breach","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_Breach","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_CombatStripGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_CombatStripTimer","LOCALS",12)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  See(SecondNearestEnemyOf(Myself))
  GlobalGT("MO_Breach","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_Breach","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_CombatStripGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_CombatStripTimer","LOCALS",12)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  See(ThirdNearestEnemyOf(Myself))
  GlobalGT("MO_Breach","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_Breach","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_CombatStripGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_CombatStripTimer","LOCALS",12)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  See(FourthNearestEnemyOf(Myself))
  GlobalGT("MO_Breach","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_Breach","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_CombatStripGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_CombatStripTimer","LOCALS",12)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  See(FifthNearestEnemyOf(Myself))
  GlobalGT("MO_Breach","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_Breach","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_CombatStripGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_CombatStripTimer","LOCALS",12)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  See(SixthNearestEnemyOf(Myself))
  GlobalGT("MO_Breach","LOCALS",0)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_Breach","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_CombatStripGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_CombatStripTimer","LOCALS",12)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Ruby Ray of Reversal
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SpellStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_SpellStripTimer","LOCALS")
  See(NearestEnemyOf(Myself))
  GlobalGT("MO_RubyRay","LOCALS",0)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_RubyRay","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_SpellStripGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_SpellStripTimer","LOCALS",12)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SpellStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_SpellStripTimer","LOCALS")
  See(SecondNearestEnemyOf(Myself))
  GlobalGT("MO_RubyRay","LOCALS",0)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_RubyRay","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_SpellStripGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_SpellStripTimer","LOCALS",12)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SpellStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_SpellStripTimer","LOCALS")
  See(ThirdNearestEnemyOf(Myself))
  GlobalGT("MO_RubyRay","LOCALS",0)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_RubyRay","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_SpellStripGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_SpellStripTimer","LOCALS",12)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SpellStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_SpellStripTimer","LOCALS")
  See(FourthNearestEnemyOf(Myself))
  GlobalGT("MO_RubyRay","LOCALS",0)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_RubyRay","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_SpellStripGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_SpellStripTimer","LOCALS",12)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SpellStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_SpellStripTimer","LOCALS")
  See(FifthNearestEnemyOf(Myself))
  GlobalGT("MO_RubyRay","LOCALS",0)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_RubyRay","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_SpellStripGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_SpellStripTimer","LOCALS",12)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SpellStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_SpellStripTimer","LOCALS")
  See(SixthNearestEnemyOf(Myself))
  GlobalGT("MO_RubyRay","LOCALS",0)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_RubyRay","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_SpellStripGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_SpellStripTimer","LOCALS",12)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Bigby's Crushing Hand
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_BigbysCrushingHandTimer","LOCALS")
  GlobalGT("MO_BigbysCrushingHand","LOCALS",0)
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SixthNearestEnemyOf(Myself),99,RESISTMAGIC)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_BigbysCrushingHandTimer","LOCALS")
  GlobalGT("MO_BigbysCrushingHand","LOCALS",0)
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(FifthNearestEnemyOf(Myself),99,RESISTMAGIC)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_BigbysCrushingHandTimer","LOCALS")
  GlobalGT("MO_BigbysCrushingHand","LOCALS",0)
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(FourthNearestEnemyOf(Myself),99,RESISTMAGIC)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_BigbysCrushingHandTimer","LOCALS")
  GlobalGT("MO_BigbysCrushingHand","LOCALS",0)
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),99,RESISTMAGIC)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_BigbysCrushingHandTimer","LOCALS")
  GlobalGT("MO_BigbysCrushingHand","LOCALS",0)
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SecondNearestEnemyOf(Myself),99,RESISTMAGIC)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_BigbysCrushingHandTimer","LOCALS")
  GlobalGT("MO_BigbysCrushingHand","LOCALS",0)
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(NearestEnemyOf(Myself),99,RESISTMAGIC)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_BigbysCrushingHandTimer","LOCALS")
  GlobalGT("MO_BigbysCrushingHand","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),99,RESISTMAGIC)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_BigbysCrushingHandTimer","LOCALS",18)
    IncrementGlobal("MO_BigbysCrushingHand","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Energy Drain
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnergyDrainTimer","LOCALS")
  GlobalGT("MO_EnergyDrain","LOCALS",0)
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !Kit(SixthNearestEnemyOf(Myself),UNDEADHUNTER)
  !CheckSpellState(SixthNearestEnemyOf(Myself),LATHANDER_BOON)
  CheckStat(SixthNearestEnemyOf(Myself),0,LEVEL_DRAIN_IMMUNITY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),35,RESISTMAGIC)
  !HasItemEquiped("AMUL21",SixthNearestEnemyOf(Myself))  // Amulet of Power
  !HasItemEquipedReal("BLUN25",SixthNearestEnemyOf(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("HAMM10",SixthNearestEnemyOf(Myself))  // Runehammer +4
  !HasItemEquipedReal("HAMM11",SixthNearestEnemyOf(Myself))  // Runehammer +5
  !HasItemEquipedReal("SW1H69",SixthNearestEnemyOf(Myself))  // Spectral Brand +5
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnergyDrainTimer","LOCALS")
  GlobalGT("MO_EnergyDrain","LOCALS",0)
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !Kit(FifthNearestEnemyOf(Myself),UNDEADHUNTER)
  !CheckSpellState(FifthNearestEnemyOf(Myself),LATHANDER_BOON)
  CheckStat(FifthNearestEnemyOf(Myself),0,LEVEL_DRAIN_IMMUNITY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),35,RESISTMAGIC)
  !HasItemEquiped("AMUL21",FifthNearestEnemyOf(Myself))  // Amulet of Power
  !HasItemEquipedReal("BLUN25",FifthNearestEnemyOf(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("HAMM10",FifthNearestEnemyOf(Myself))  // Runehammer +4
  !HasItemEquipedReal("HAMM11",FifthNearestEnemyOf(Myself))  // Runehammer +5
  !HasItemEquipedReal("SW1H69",FifthNearestEnemyOf(Myself))  // Spectral Brand +5
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnergyDrainTimer","LOCALS")
  GlobalGT("MO_EnergyDrain","LOCALS",0)
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !Kit(FourthNearestEnemyOf(Myself),UNDEADHUNTER)
  !CheckSpellState(FourthNearestEnemyOf(Myself),LATHANDER_BOON)
  CheckStat(FourthNearestEnemyOf(Myself),0,LEVEL_DRAIN_IMMUNITY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),35,RESISTMAGIC)
  !HasItemEquiped("AMUL21",FourthNearestEnemyOf(Myself))  // Amulet of Power
  !HasItemEquipedReal("BLUN25",FourthNearestEnemyOf(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("HAMM10",FourthNearestEnemyOf(Myself))  // Runehammer +4
  !HasItemEquipedReal("HAMM11",FourthNearestEnemyOf(Myself))  // Runehammer +5
  !HasItemEquipedReal("SW1H69",FourthNearestEnemyOf(Myself))  // Spectral Brand +5
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnergyDrainTimer","LOCALS")
  GlobalGT("MO_EnergyDrain","LOCALS",0)
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !Kit(ThirdNearestEnemyOf(Myself),UNDEADHUNTER)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),LATHANDER_BOON)
  CheckStat(ThirdNearestEnemyOf(Myself),0,LEVEL_DRAIN_IMMUNITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),35,RESISTMAGIC)
  !HasItemEquiped("AMUL21",ThirdNearestEnemyOf(Myself))  // Amulet of Power
  !HasItemEquipedReal("BLUN25",ThirdNearestEnemyOf(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("HAMM10",ThirdNearestEnemyOf(Myself))  // Runehammer +4
  !HasItemEquipedReal("HAMM11",ThirdNearestEnemyOf(Myself))  // Runehammer +5
  !HasItemEquipedReal("SW1H69",ThirdNearestEnemyOf(Myself))  // Spectral Brand +5
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnergyDrainTimer","LOCALS")
  GlobalGT("MO_EnergyDrain","LOCALS",0)
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !Kit(SecondNearestEnemyOf(Myself),UNDEADHUNTER)
  !CheckSpellState(SecondNearestEnemyOf(Myself),LATHANDER_BOON)
  CheckStat(SecondNearestEnemyOf(Myself),0,LEVEL_DRAIN_IMMUNITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),35,RESISTMAGIC)
  !HasItemEquiped("AMUL21",SecondNearestEnemyOf(Myself))  // Amulet of Power
  !HasItemEquipedReal("BLUN25",SecondNearestEnemyOf(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("HAMM10",SecondNearestEnemyOf(Myself))  // Runehammer +4
  !HasItemEquipedReal("HAMM11",SecondNearestEnemyOf(Myself))  // Runehammer +5
  !HasItemEquipedReal("SW1H69",SecondNearestEnemyOf(Myself))  // Spectral Brand +5
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnergyDrainTimer","LOCALS")
  GlobalGT("MO_EnergyDrain","LOCALS",0)
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  !CheckSpellState(NearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !Kit(NearestEnemyOf(Myself),UNDEADHUNTER)
  !CheckSpellState(NearestEnemyOf(Myself),LATHANDER_BOON)
  CheckStat(NearestEnemyOf(Myself),0,LEVEL_DRAIN_IMMUNITY)
  !CheckStatGT(NearestEnemyOf(Myself),35,RESISTMAGIC)
  !HasItemEquiped("AMUL21",NearestEnemyOf(Myself))  // Amulet of Power
  !HasItemEquipedReal("BLUN25",NearestEnemyOf(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("HAMM10",NearestEnemyOf(Myself))  // Runehammer +4
  !HasItemEquipedReal("HAMM11",NearestEnemyOf(Myself))  // Runehammer +5
  !HasItemEquipedReal("SW1H69",NearestEnemyOf(Myself))  // Spectral Brand +5
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_EnergyDrainTimer","LOCALS")
  GlobalGT("MO_EnergyDrain","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),LATHANDER_BOON)
  CheckStat(LastSeenBy(Myself),0,LEVEL_DRAIN_IMMUNITY)
  !CheckStatGT(LastSeenBy(Myself),35,RESISTMAGIC)
  !HasItemEquiped("AMUL21",Myself)  // Amulet of Power
  !HasItemEquipedReal("BLUN25",LastSeenBy(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("HAMM10",LastSeenBy(Myself))  // Runehammer +4
  !HasItemEquipedReal("HAMM11",LastSeenBy(Myself))  // Runehammer +5
  !HasItemEquipedReal("SW1H69",LastSeenBy(Myself))  // Spectral Brand +5
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnergyDrainTimer","LOCALS",18)
    IncrementGlobal("MO_EnergyDrain","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ENERGY_DRAIN)  // SPWI914.SPL (Energy Drain)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Greater Malison
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MalisonTimer","LOCALS")
  GlobalGT("MO_Malison","LOCALS",0)
  !CheckSpellState(SixthNearestEnemyOf(Myself),MALISON)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MalisonTimer","LOCALS")
  GlobalGT("MO_Malison","LOCALS",0)
  !CheckSpellState(FifthNearestEnemyOf(Myself),MALISON)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MalisonTimer","LOCALS")
  GlobalGT("MO_Malison","LOCALS",0)
  !CheckSpellState(FourthNearestEnemyOf(Myself),MALISON)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MalisonTimer","LOCALS")
  GlobalGT("MO_Malison","LOCALS",0)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),MALISON)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MalisonTimer","LOCALS")
  GlobalGT("MO_Malison","LOCALS",0)
  !CheckSpellState(SecondNearestEnemyOf(Myself),MALISON)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_ENCHANTMENT)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MalisonTimer","LOCALS")
  GlobalGT("MO_Malison","LOCALS",0)
  !CheckSpellState(NearestEnemyOf(Myself),MALISON)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  !CheckSpellState(NearestEnemyOf(Myself),SI_ENCHANTMENT)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MalisonTimer","LOCALS")
  GlobalGT("MO_Malison","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckSpellState(LastSeenBy(Myself),MALISON)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MalisonTimer","LOCALS",18)
    IncrementGlobal("MO_Malison","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Teleport Field
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_TeleportTimer","LOCALS")
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  GlobalGT("MO_Teleport","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    IncrementGlobal("MO_Teleport","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_TeleportTimer","LOCALS",60)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_TELEPORT_FIELD)
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Maze
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  GlobalGT("MO_Maze","LOCALS",0)
  Range(SixthNearestEnemyOf(Myself),4)
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SixthNearestEnemyOf(Myself),18,INT)
  !CheckSpellState(SixthNearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(SixthNearestEnemyOf(Myself),25,RESISTMAGIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HARMLESS)
  !Kit(SixthNearestEnemyOf(Myself),BERSERKER)
  !Kit(SixthNearestEnemyOf(Myself),BARBARIAN)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  GlobalGT("MO_Maze","LOCALS",0)
  Range(FifthNearestEnemyOf(Myself),4)
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FifthNearestEnemyOf(Myself),18,INT)
  !CheckSpellState(FifthNearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(FifthNearestEnemyOf(Myself),25,RESISTMAGIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HARMLESS)
  !Kit(FifthNearestEnemyOf(Myself),BERSERKER)
  !Kit(FifthNearestEnemyOf(Myself),BARBARIAN)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  GlobalGT("MO_Maze","LOCALS",0)
  Range(FourthNearestEnemyOf(Myself),4)
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FourthNearestEnemyOf(Myself),18,INT)
  !CheckSpellState(FourthNearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(FourthNearestEnemyOf(Myself),25,RESISTMAGIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HARMLESS)
  !Kit(FourthNearestEnemyOf(Myself),BERSERKER)
  !Kit(FourthNearestEnemyOf(Myself),BARBARIAN)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  GlobalGT("MO_Maze","LOCALS",0)
  Range(ThirdNearestEnemyOf(Myself),4)
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(ThirdNearestEnemyOf(Myself),18,INT)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),25,RESISTMAGIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HARMLESS)
  !Kit(ThirdNearestEnemyOf(Myself),BERSERKER)
  !Kit(ThirdNearestEnemyOf(Myself),BARBARIAN)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  GlobalGT("MO_Maze","LOCALS",0)
  Range(SecondNearestEnemyOf(Myself),4)
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SecondNearestEnemyOf(Myself),18,INT)
  !CheckSpellState(SecondNearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(SecondNearestEnemyOf(Myself),25,RESISTMAGIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HARMLESS)
  !Kit(SecondNearestEnemyOf(Myself),BERSERKER)
  !Kit(SecondNearestEnemyOf(Myself),BARBARIAN)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  GlobalGT("MO_Maze","LOCALS",0)
  Range(NearestEnemyOf(Myself),4)
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(NearestEnemyOf(Myself),18,INT)
  !CheckSpellState(NearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(NearestEnemyOf(Myself),25,RESISTMAGIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(NearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(NearestEnemyOf(Myself),STATE_HARMLESS)
  !Kit(NearestEnemyOf(Myself),BERSERKER)
  !Kit(NearestEnemyOf(Myself),BARBARIAN)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  GlobalGT("MO_Maze","LOCALS",0)
  Range(SixthNearestEnemyOf(Myself),4)
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SixthNearestEnemyOf(Myself),12,INT)
  !CheckSpellState(SixthNearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(SixthNearestEnemyOf(Myself),25,RESISTMAGIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HARMLESS)
  !Kit(SixthNearestEnemyOf(Myself),BERSERKER)
  !Kit(SixthNearestEnemyOf(Myself),BARBARIAN)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  GlobalGT("MO_Maze","LOCALS",0)
  Range(FifthNearestEnemyOf(Myself),4)
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FifthNearestEnemyOf(Myself),12,INT)
  !CheckSpellState(FifthNearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(FifthNearestEnemyOf(Myself),25,RESISTMAGIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HARMLESS)
  !Kit(FifthNearestEnemyOf(Myself),BERSERKER)
  !Kit(FifthNearestEnemyOf(Myself),BARBARIAN)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  GlobalGT("MO_Maze","LOCALS",0)
  Range(FourthNearestEnemyOf(Myself),4)
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FourthNearestEnemyOf(Myself),12,INT)
  !CheckSpellState(FourthNearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(FourthNearestEnemyOf(Myself),25,RESISTMAGIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HARMLESS)
  !Kit(FourthNearestEnemyOf(Myself),BERSERKER)
  !Kit(FourthNearestEnemyOf(Myself),BARBARIAN)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  GlobalGT("MO_Maze","LOCALS",0)
  Range(ThirdNearestEnemyOf(Myself),4)
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(ThirdNearestEnemyOf(Myself),12,INT)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),25,RESISTMAGIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HARMLESS)
  !Kit(ThirdNearestEnemyOf(Myself),BERSERKER)
  !Kit(ThirdNearestEnemyOf(Myself),BARBARIAN)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  GlobalGT("MO_Maze","LOCALS",0)
  Range(SecondNearestEnemyOf(Myself),4)
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SecondNearestEnemyOf(Myself),12,INT)
  !CheckSpellState(SecondNearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(SecondNearestEnemyOf(Myself),25,RESISTMAGIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HARMLESS)
  !Kit(SecondNearestEnemyOf(Myself),BERSERKER)
  !Kit(SecondNearestEnemyOf(Myself),BARBARIAN)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  GlobalGT("MO_Maze","LOCALS",0)
  Range(NearestEnemyOf(Myself),4)
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(NearestEnemyOf(Myself),12,INT)
  !CheckSpellState(NearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(NearestEnemyOf(Myself),25,RESISTMAGIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(NearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(NearestEnemyOf(Myself),STATE_HARMLESS)
  !Kit(NearestEnemyOf(Myself),BERSERKER)
  !Kit(NearestEnemyOf(Myself),BARBARIAN)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  GlobalGT("MO_Maze","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),4)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    IncrementGlobal("MO_Maze","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAZE)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Death Spell
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DeathSpellTimer","GLOBAL")
  GlobalGT("MO_DeathSpell","LOCALS",0)
  See(Nearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_DeathSpellTimer","GLOBAL",18)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
  RESPONSE #20
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Power Word, Stun
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  GlobalGT("MO_PowerWordStun","LOCALS",0)
  HPLT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),90)
  HPPercentLT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),60)
  !Gender(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),SUMMONED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),BERSERKER_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),MINSC_BERSERK)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),CHAOTIC_COMMANDS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),SI_CONJURATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),0,SANCTUARY)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),STATE_HARMLESS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  GlobalGT("MO_PowerWordStun","LOCALS",0)
  HPLT([GOODCUTOFF.0.0.DRUID_ALL],90)
  HPPercentLT([GOODCUTOFF.0.0.DRUID_ALL],60)
  !Gender([GOODCUTOFF.0.0.DRUID_ALL],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.DRUID_ALL],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.DRUID_ALL],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.DRUID_ALL],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.DRUID_ALL],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.DRUID_ALL],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.DRUID_ALL],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.DRUID_ALL],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState([GOODCUTOFF.0.0.DRUID_ALL],CHAOTIC_COMMANDS)
  !CheckSpellState([GOODCUTOFF.0.0.DRUID_ALL],SI_CONJURATION)
  !StateCheck([GOODCUTOFF.0.0.DRUID_ALL],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.DRUID_ALL],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.DRUID_ALL],0,SANCTUARY)
  !StateCheck([GOODCUTOFF.0.0.DRUID_ALL],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.DRUID_ALL],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.DRUID_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  GlobalGT("MO_PowerWordStun","LOCALS",0)
  HPLT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),90)
  HPPercentLT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),60)
  !Gender(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),SUMMONED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),BERSERKER_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),MINSC_BERSERK)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),CHAOTIC_COMMANDS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),SI_CONJURATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),0,SANCTUARY)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),STATE_HARMLESS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  GlobalGT("MO_PowerWordStun","LOCALS",0)
  HPLT([GOODCUTOFF.0.0.CLERIC_ALL],90)
  HPPercentLT([GOODCUTOFF.0.0.CLERIC_ALL],60)
  !Gender([GOODCUTOFF.0.0.CLERIC_ALL],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.CLERIC_ALL],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.CLERIC_ALL],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.CLERIC_ALL],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.CLERIC_ALL],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.CLERIC_ALL],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.CLERIC_ALL],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.CLERIC_ALL],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState([GOODCUTOFF.0.0.CLERIC_ALL],CHAOTIC_COMMANDS)
  !CheckSpellState([GOODCUTOFF.0.0.CLERIC_ALL],SI_CONJURATION)
  !StateCheck([GOODCUTOFF.0.0.CLERIC_ALL],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.CLERIC_ALL],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.CLERIC_ALL],0,SANCTUARY)
  !StateCheck([GOODCUTOFF.0.0.CLERIC_ALL],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.CLERIC_ALL],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.CLERIC_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  GlobalGT("MO_PowerWordStun","LOCALS",0)
  HPLT(SecondNearest([GOODCUTOFF.0.0.THIEF]),90)
  HPPercentLT(SecondNearest([GOODCUTOFF.0.0.THIEF]),60)
  !Gender(SecondNearest([GOODCUTOFF.0.0.THIEF]),SUMMONED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),BERSERKER_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),MINSC_BERSERK)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),CHAOTIC_COMMANDS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),SI_CONJURATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.THIEF]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.THIEF]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),0,SANCTUARY)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.THIEF]),STATE_HARMLESS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.THIEF]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  GlobalGT("MO_PowerWordStun","LOCALS",0)
  HPLT([GOODCUTOFF.0.0.THIEF],90)
  HPPercentLT([GOODCUTOFF.0.0.THIEF],60)
  !Gender([GOODCUTOFF.0.0.THIEF],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.THIEF],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.THIEF],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.THIEF],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.THIEF],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],CHAOTIC_COMMANDS)
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],SI_CONJURATION)
  !StateCheck([GOODCUTOFF.0.0.THIEF],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.THIEF],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],0,SANCTUARY)
  !StateCheck([GOODCUTOFF.0.0.THIEF],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.THIEF])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  GlobalGT("MO_PowerWordStun","LOCALS",0)
  HPLT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),90)
  HPPercentLT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),60)
  !Gender(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),SUMMONED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),BERSERKER_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),MINSC_BERSERK)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),CHAOTIC_COMMANDS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),SI_CONJURATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),0,SANCTUARY)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),STATE_HARMLESS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  GlobalGT("MO_PowerWordStun","LOCALS",0)
  HPLT([GOODCUTOFF.0.0.BARD_ALL],90)
  HPPercentLT([GOODCUTOFF.0.0.BARD_ALL],60)
  !Gender([GOODCUTOFF.0.0.BARD_ALL],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.BARD_ALL],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.BARD_ALL],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.BARD_ALL],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.BARD_ALL],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.BARD_ALL],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.BARD_ALL],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.BARD_ALL],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState([GOODCUTOFF.0.0.BARD_ALL],CHAOTIC_COMMANDS)
  !CheckSpellState([GOODCUTOFF.0.0.BARD_ALL],SI_CONJURATION)
  !StateCheck([GOODCUTOFF.0.0.BARD_ALL],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.BARD_ALL],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.BARD_ALL],0,SANCTUARY)
  !StateCheck([GOODCUTOFF.0.0.BARD_ALL],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.BARD_ALL],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.BARD_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  GlobalGT("MO_PowerWordStun","LOCALS",0)
  HPLT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),90)
  HPPercentLT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),60)
  !Gender(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),SUMMONED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),BARBARIAN_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),BERSERKER_RAGE)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),MINSC_BERSERK)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),CHAOTIC_COMMANDS)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),SI_CONJURATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),0,SANCTUARY)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),STATE_HARMLESS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  GlobalGT("MO_PowerWordStun","LOCALS",0)
  HPLT([GOODCUTOFF.0.0.MAGE_ALL],90)
  HPPercentLT([GOODCUTOFF.0.0.MAGE_ALL],60)
  !Gender([GOODCUTOFF.0.0.MAGE_ALL],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_ALL],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_ALL],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_ALL],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.MAGE_ALL],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.MAGE_ALL],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.MAGE_ALL],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.MAGE_ALL],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_ALL],CHAOTIC_COMMANDS)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_ALL],SI_CONJURATION)
  !StateCheck([GOODCUTOFF.0.0.MAGE_ALL],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.MAGE_ALL],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_ALL],0,SANCTUARY)
  !StateCheck([GOODCUTOFF.0.0.MAGE_ALL],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_ALL],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.MAGE_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  GlobalGT("MO_PowerWordStun","LOCALS",0)
  HPLT([GOODCUTOFF.0.0.MAGE_THIEF],90)
  HPPercentLT([GOODCUTOFF.0.0.MAGE_THIEF],60)
  !Gender([GOODCUTOFF.0.0.MAGE_THIEF],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_THIEF],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_THIEF],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_THIEF],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.MAGE_THIEF],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.MAGE_THIEF],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.MAGE_THIEF],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.MAGE_THIEF],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_THIEF],CHAOTIC_COMMANDS)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE_THIEF],SI_CONJURATION)
  !StateCheck([GOODCUTOFF.0.0.MAGE_THIEF],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.MAGE_THIEF],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_THIEF],0,SANCTUARY)
  !StateCheck([GOODCUTOFF.0.0.MAGE_THIEF],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE_THIEF],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.MAGE_THIEF])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  GlobalGT("MO_PowerWordStun","LOCALS",0)
  HPLT([GOODCUTOFF.0.0.MAGE],90)
  HPPercentLT([GOODCUTOFF.0.0.MAGE],60)
  !Gender([GOODCUTOFF.0.0.MAGE],SUMMONED)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE],BARBARIAN_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE],BERSERKER_RAGE)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE],MINSC_BERSERK)
  CheckStatLT([GOODCUTOFF.0.0.MAGE],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.MAGE],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.MAGE],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.MAGE],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE],CHAOTIC_COMMANDS)
  !CheckSpellState([GOODCUTOFF.0.0.MAGE],SI_CONJURATION)
  !StateCheck([GOODCUTOFF.0.0.MAGE],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.MAGE],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE],0,SANCTUARY)
  !StateCheck([GOODCUTOFF.0.0.MAGE],STATE_HARMLESS)
  !CheckStatGT([GOODCUTOFF.0.0.MAGE],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.MAGE])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_StunTimer","LOCALS")
  GlobalGT("MO_PowerWordStun","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HPLT(LastSeenBy(Myself),90)
  HPPercentLT(LastSeenBy(Myself),60)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_StunTimer","LOCALS",12)
    IncrementGlobal("MO_PowerWordStun","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Slow
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  GlobalGT("MO_Slow","LOCALS",0)
  !HasItemEquiped("RING09",SecondNearest([GOODCUTOFF.0.0.THIEF])) // Ring of Free Action
  !HasItemEquiped("NPSW01",SecondNearest([GOODCUTOFF.0.0.THIEF])) // Sword of Avoreen
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),SI_TRANSMUTATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.THIEF]),STATE_HARMLESS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.THIEF]),STATE_SLOWED)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.THIEF]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.THIEF]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),0,SANCTUARY)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.THIEF]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),0,MINORGLOBE)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),0,CLERIC_FREE_ACTION)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.THIEF]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  GlobalGT("MO_Slow","LOCALS",0)
  !HasItemEquiped("RING09",[GOODCUTOFF.0.0.THIEF]) // Ring of Free Action
  !HasItemEquiped("NPSW01",[GOODCUTOFF.0.0.THIEF]) // Sword of Avoreen
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],SI_TRANSMUTATION)
  !StateCheck([GOODCUTOFF.0.0.THIEF],STATE_HARMLESS)
  !StateCheck([GOODCUTOFF.0.0.THIEF],STATE_SLOWED)
  !StateCheck([GOODCUTOFF.0.0.THIEF],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.THIEF],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],0,SANCTUARY)
  CheckStatLT([GOODCUTOFF.0.0.THIEF],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.THIEF],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.THIEF],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.THIEF],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],0,MINORGLOBE)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],0,CLERIC_FREE_ACTION)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.THIEF])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  GlobalGT("MO_Slow","LOCALS",0)
  !HasItemEquiped("RING09",SecondNearest([GOODCUTOFF.0.0.RANGER_ALL])) // Ring of Free Action
  !HasItemEquiped("NPSW01",SecondNearest([GOODCUTOFF.0.0.RANGER_ALL])) // Sword of Avoreen
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),SI_TRANSMUTATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),STATE_HARMLESS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),STATE_SLOWED)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),0,SANCTUARY)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),0,MINORGLOBE)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),0,CLERIC_FREE_ACTION)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  GlobalGT("MO_Slow","LOCALS",0)
  !HasItemEquiped("RING09",[GOODCUTOFF.0.0.RANGER_ALL]) // Ring of Free Action
  !HasItemEquiped("NPSW01",[GOODCUTOFF.0.0.RANGER_ALL]) // Sword of Avoreen
  !CheckSpellState([GOODCUTOFF.0.0.RANGER_ALL],SI_TRANSMUTATION)
  !StateCheck([GOODCUTOFF.0.0.RANGER_ALL],STATE_HARMLESS)
  !StateCheck([GOODCUTOFF.0.0.RANGER_ALL],STATE_SLOWED)
  !StateCheck([GOODCUTOFF.0.0.RANGER_ALL],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.RANGER_ALL],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.RANGER_ALL],0,SANCTUARY)
  CheckStatLT([GOODCUTOFF.0.0.RANGER_ALL],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.RANGER_ALL],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.RANGER_ALL],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.RANGER_ALL],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT([GOODCUTOFF.0.0.RANGER_ALL],0,MINORGLOBE)
  !CheckStatGT([GOODCUTOFF.0.0.RANGER_ALL],0,CLERIC_FREE_ACTION)
  !CheckStatGT([GOODCUTOFF.0.0.RANGER_ALL],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.RANGER_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  GlobalGT("MO_Slow","LOCALS",0)
  !HasItemEquiped("RING09",SecondNearest([GOODCUTOFF.0.0.PALADIN])) // Ring of Free Action
  !HasItemEquiped("NPSW01",SecondNearest([GOODCUTOFF.0.0.PALADIN])) // Sword of Avoreen
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.PALADIN]),SI_TRANSMUTATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.PALADIN]),STATE_HARMLESS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.PALADIN]),STATE_SLOWED)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.PALADIN]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.PALADIN]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),0,SANCTUARY)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.PALADIN]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.PALADIN]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),0,MINORGLOBE)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),0,CLERIC_FREE_ACTION)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.PALADIN]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  GlobalGT("MO_Slow","LOCALS",0)
  !HasItemEquiped("RING09",[GOODCUTOFF.0.0.PALADIN]) // Ring of Free Action
  !HasItemEquiped("NPSW01",[GOODCUTOFF.0.0.PALADIN]) // Sword of Avoreen
  !CheckSpellState([GOODCUTOFF.0.0.PALADIN],SI_TRANSMUTATION)
  !StateCheck([GOODCUTOFF.0.0.PALADIN],STATE_HARMLESS)
  !StateCheck([GOODCUTOFF.0.0.PALADIN],STATE_SLOWED)
  !StateCheck([GOODCUTOFF.0.0.PALADIN],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.PALADIN],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.PALADIN],0,SANCTUARY)
  CheckStatLT([GOODCUTOFF.0.0.PALADIN],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.PALADIN],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.PALADIN],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.PALADIN],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT([GOODCUTOFF.0.0.PALADIN],0,MINORGLOBE)
  !CheckStatGT([GOODCUTOFF.0.0.PALADIN],0,CLERIC_FREE_ACTION)
  !CheckStatGT([GOODCUTOFF.0.0.PALADIN],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.PALADIN])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  GlobalGT("MO_Slow","LOCALS",0)
  !Class(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),MONK)
  !HasItemEquiped("RING09",SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL])) // Ring of Free Action
  !HasItemEquiped("NPSW01",SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL])) // Sword of Avoreen
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),SI_TRANSMUTATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),STATE_HARMLESS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),STATE_SLOWED)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),0,SANCTUARY)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),0,MINORGLOBE)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),0,CLERIC_FREE_ACTION)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  GlobalGT("MO_Slow","LOCALS",0)
  !Class([GOODCUTOFF.0.0.FIGHTER_ALL],MONK)
  !HasItemEquiped("RING09",[GOODCUTOFF.0.0.FIGHTER_ALL]) // Ring of Free Action
  !HasItemEquiped("NPSW01",[GOODCUTOFF.0.0.FIGHTER_ALL]) // Sword of Avoreen
  !CheckSpellState([GOODCUTOFF.0.0.FIGHTER_ALL],SI_TRANSMUTATION)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER_ALL],STATE_HARMLESS)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER_ALL],STATE_SLOWED)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER_ALL],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER_ALL],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER_ALL],0,SANCTUARY)
  CheckStatLT([GOODCUTOFF.0.0.FIGHTER_ALL],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.FIGHTER_ALL],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.FIGHTER_ALL],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.FIGHTER_ALL],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER_ALL],0,MINORGLOBE)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER_ALL],0,CLERIC_FREE_ACTION)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER_ALL],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.FIGHTER_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  GlobalGT("MO_Slow","LOCALS",0)
  !Class(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),MONK)
  !HasItemEquiped("RING09",SecondNearest([GOODCUTOFF.0.0.FIGHTER])) // Ring of Free Action
  !HasItemEquiped("NPSW01",SecondNearest([GOODCUTOFF.0.0.FIGHTER])) // Sword of Avoreen
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),SI_TRANSMUTATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),STATE_HARMLESS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),STATE_SLOWED)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),0,SANCTUARY)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),0,MINORGLOBE)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),0,CLERIC_FREE_ACTION)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.FIGHTER]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  GlobalGT("MO_Slow","LOCALS",0)
  !Class([GOODCUTOFF.0.0.FIGHTER],MONK)
  !HasItemEquiped("RING09",[GOODCUTOFF.0.0.FIGHTER]) // Ring of Free Action
  !HasItemEquiped("NPSW01",[GOODCUTOFF.0.0.FIGHTER]) // Sword of Avoreen
  !CheckSpellState([GOODCUTOFF.0.0.FIGHTER],SI_TRANSMUTATION)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER],STATE_HARMLESS)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER],STATE_SLOWED)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER],STATE_NOT_TARGETABLE)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER],STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER],0,SANCTUARY)
  CheckStatLT([GOODCUTOFF.0.0.FIGHTER],1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT([GOODCUTOFF.0.0.FIGHTER],1,WIZARD_SPELL_TURNING)
  !CheckStat([GOODCUTOFF.0.0.FIGHTER],1,WIZARD_SPELL_TRAP)
  !CheckStat([GOODCUTOFF.0.0.FIGHTER],1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER],0,MINORGLOBE)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER],0,CLERIC_FREE_ACTION)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.FIGHTER])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  GlobalGT("MO_Slow","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !Class(LastSeenBy(Myself),MONK)
  !HasItemEquiped("RING09",LastSeenBy(Myself)) // Ring of Free Action
  !HasItemEquiped("NPSW01",LastSeenBy(Myself)) // Sword of Avoreen
  !CheckSpellState(LastSeenBy(Myself),SI_TRANSMUTATION)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_SlowTimer","LOCALS",18)
    IncrementGlobal("MO_Slow","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Contagion
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ContagionTimer","LOCALS")
  GlobalGT("MO_Contagion","LOCALS",0)
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HARMLESS)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ContagionTimer","LOCALS")
  GlobalGT("MO_Contagion","LOCALS",0)
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HARMLESS)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ContagionTimer","LOCALS")
  GlobalGT("MO_Contagion","LOCALS",0)
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HARMLESS)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ContagionTimer","LOCALS")
  GlobalGT("MO_Contagion","LOCALS",0)
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HARMLESS)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ContagionTimer","LOCALS")
  GlobalGT("MO_Contagion","LOCALS",0)
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HARMLESS)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ContagionTimer","LOCALS")
  GlobalGT("MO_Contagion","LOCALS",0)
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  !CheckSpellState(NearestEnemyOf(Myself),SI_NECROMANCY)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(NearestEnemyOf(Myself),STATE_HARMLESS)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ContagionTimer","LOCALS")
  GlobalGT("MO_Contagion","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_ContagionTimer","LOCALS",18)
    IncrementGlobal("MO_Contagion","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CONTAGION)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Unholy Word
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_UnholyWord","LOCALS",0)
  Alignment(SixthNearestEnemyOf(Myself),MASK_GOOD)
  Alignment(Myself,MASK_EVIL)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HARMLESS)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_UnholyWord","LOCALS",0)
  Alignment(FifthNearestEnemyOf(Myself),MASK_GOOD)
  Alignment(Myself,MASK_EVIL)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HARMLESS)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_UnholyWord","LOCALS",0)
  Alignment(FourthNearestEnemyOf(Myself),MASK_GOOD)
  Alignment(Myself,MASK_EVIL)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HARMLESS)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_UnholyWord","LOCALS",0)
  Alignment(ThirdNearestEnemyOf(Myself),MASK_GOOD)
  Alignment(Myself,MASK_EVIL)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HARMLESS)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_UnholyWord","LOCALS",0)
  Alignment(SecondNearestEnemyOf(Myself),MASK_GOOD)
  Alignment(Myself,MASK_EVIL)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HARMLESS)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_UnholyWord","LOCALS",0)
  Alignment(NearestEnemyOf(Myself),MASK_GOOD)
  Alignment(Myself,MASK_EVIL)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(NearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(NearestEnemyOf(Myself),STATE_HARMLESS)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_UnholyWord","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Alignment(LastSeenBy(Myself),MASK_GOOD)
  Alignment(Myself,MASK_EVIL)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,40,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,80)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MO_UnholyWord","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Shadow Door
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(NearestEnemyOf(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("MO_ShadowDoor","LOCALS",0)
  CheckSpellState(Myself,SI_DIVINATION)
  !StateCheck(Myself,STATE_INVISIBLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_ShadowDoor","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_SHADOW_DOOR)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Wondrous Recall
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_WondrousRecallCounter","LOCALS",1)
  See(NearestEnemyOf(Myself))
  GlobalGT("MO_WondrousRecall","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    IncrementGlobal("MO_WondrousRecall","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,CLERIC_WONDROUS_RECALL)  // SPPR611.SPL (Wondrous Recall)
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: WIZARD_LARLOCH_MINOR_DRAIN
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(NearestEnemyOf(Myself))
  GlobalGT("MO_Larloch","LOCALS",0)
  Range(LastSeenBy(Myself),4)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_Larloch","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(SecondNearestEnemyOf(Myself))
  GlobalGT("MO_Larloch","LOCALS",0)
  Range(LastSeenBy(Myself),4)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_Larloch","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(ThirdNearestEnemyOf(Myself))
  GlobalGT("MO_Larloch","LOCALS",0)
  Range(LastSeenBy(Myself),4)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_Larloch","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(FourthNearestEnemyOf(Myself))
  GlobalGT("MO_Larloch","LOCALS",0)
  Range(LastSeenBy(Myself),4)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_Larloch","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(FifthNearestEnemyOf(Myself))
  GlobalGT("MO_Larloch","LOCALS",0)
  Range(LastSeenBy(Myself),4)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_Larloch","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(SixthNearestEnemyOf(Myself))
  GlobalGT("MO_Larloch","LOCALS",0)
  Range(LastSeenBy(Myself),4)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_Larloch","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
    SetInterrupt(TRUE)
END